#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

redirect_cmd exec s6-setuidgid hotio mono --debug "${APP_DIR}/NzbDrone.exe" --nobrowser --data="${CONFIG_DIR}/app"
