#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ "${BACKUP}" == "yes" ]]; then
    BACKUP_PATH="${CONFIG_DIR}/app-backups/${APP}_backup_$(date +%Y.%m.%d_%H.%M.%S).tar.gz"
    tar -czf "${BACKUP_PATH}" -C "${CONFIG_DIR}" "app/nzbdrone.db" "app/config.xml"
    chown hotio:hotio "${BACKUP_PATH}"
fi
