#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
APP=${APP}
GIT_COMMIT=${GIT_COMMIT}
GIT_TAG=${GIT_TAG}
ARCH=${ARCH}
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
VERSION=${VERSION}
TZ=${TZ}
RCLONE=${RCLONE}
RAR2FS=${RAR2FS}
----------------------------------------------------------------------
"

groupmod -o -g "${PGID}" hotio
usermod -o -u "${PUID}" hotio

if [[ ! -d "${CONFIG_DIR}/app" ]]; then
    mkdir "${CONFIG_DIR}/app"
    chown hotio:hotio "${CONFIG_DIR}/app"
fi
